export const PORTFOLIO = {
  name: "Bashar V Ismail",
  role: "Full Stack Developer",
  location: "Kerala, India",
  timezone: "Asia/Kolkata",
  email: "basharvismail@gmail.com",
  phone: "+91 9847014566",
  github: "bashar-vi",
  linkedin: "bashar-vi",
  resumeUrl: "/resume/Bashar_Ismail_Resume.pdf",
  status: {
    available: true,
    message: "Available for immediate joining · Open to FS / backend roles",
    currentlyBuilding: "MERN stack apps & microservices",
  },
  taglines: [
    "build_systems_that_ship",
    "react · node · mongodb · docker",
    "4+_yrs_shipping_web_software",
    "mern_stack_developer",
    "ex-baggagetaxi_dubai · ex-skyniche",
  ],
  about: [
    "I'm a Full Stack Developer with 4+ years of experience building end-to-end web applications, including 1 year of hands-on development in Dubai, UAE.",
    "I specialize in the MERN stack — MongoDB, Express.js, React.js, Node.js — with additional expertise in Next.js, NestJS, and Docker. I've shipped SaaS platforms, logistics systems, and AI-integrated tools.",
    "Currently based in Kerala, India and available for immediate joining. I thrive in Agile environments and own the full software development lifecycle from database schema to production deploy.",
  ],
  skills: {
    frontend: [
      { name: "React.js / Next.js", level: 92 },
      { name: "TypeScript / JavaScript", level: 88 },
      { name: "Tailwind CSS / Bootstrap", level: 85 },
      { name: "Redux", level: 80 },
      { name: "Astro.js", level: 72 },
    ],
    backend: [
      { name: "Node.js / Express.js", level: 92 },
      { name: "NestJS / Fastify", level: 82 },
      { name: "MongoDB / Mongoose", level: 88 },
      { name: "RESTful APIs / JWT", level: 90 },
      { name: "Microservices", level: 78 },
    ],
    devops: [
      { name: "Docker", level: 82 },
      { name: "CI/CD / GitHub Actions", level: 80 },
      { name: "Git / GitHub / GitLab", level: 90 },
      { name: "Stripe API", level: 80 },
      { name: "Jest / Postman", level: 78 },
    ],
    tooling: [
      { name: "MongoDB / SQL", level: 85 },
      { name: "OpenAI APIs", level: 78 },
      { name: "WordPress / Shopify", level: 70 },
      { name: "SEO Optimization", level: 75 },
      { name: "Agile / Scrum", level: 88 },
    ],
  },
  experience: [
    {
      role: "Software Engineer",
      org: "BaggageTAXI FZ-LLC",
      location: "Dubai, UAE",
      period: "July 2024 — Sept 2025",
      bullets: [
        "Developed and deployed a high-performance booking platform using Next.js and Astro.js, serving over 10,000 active users.",
        "Led design and implementation of scalable backend microservices with NestJS, MongoDB, and JWT authentication.",
        "Integrated CI/CD pipelines with GitHub Actions, reducing release times and eliminating manual deployment errors.",
        "Executed thorough E2E testing using Postman, Jest, and manual test cases ensuring high-quality production releases.",
      ],
    },
    {
      role: "Full Stack Developer",
      org: "Freelance",
      location: "Remote",
      period: "Jan 2024 — Apr 2024",
      bullets: [
        "Delivered AI-powered web tools, admin dashboards, and Stripe-integrated SaaS platforms.",
        "Integrated OpenAI APIs for content generation, chat automation, and smart search capabilities.",
        "Built Stripe integrations for payment processing, subscription billing, and automated invoice generation.",
        "Deployed applications using Docker containers and CI/CD pipelines with GitHub Actions.",
      ],
    },
    {
      role: "Full Stack Developer",
      org: "Skyniche Technologies",
      location: "Kerala, India",
      period: "Feb 2021 — Dec 2023",
      bullets: [
        "Designed and developed ManageBee, a scalable SaaS platform for end-to-end property inspection and management.",
        "Delivered full-stack features: dashboards, dynamic inspection forms, automated PDF reporting, and email notifications.",
        "Integrated Stripe billing and implemented role-based access control (RBAC) for admins, staff, and clients.",
        "Optimized backend API performance, achieving a 40% reduction in data processing time via query optimization.",
      ],
    },
  ],
  featured: [
    {
      id: "baggagetaxi",
      year: "2024–2025",
      title: "BaggageTAXI",
      sub: "Logistics Booking Platform · Dubai, UAE",
      desc: "End-to-end platform for customer bookings, dispatch assignment, and admin operations. Led full-stack development serving 10,000+ active users with real-time dispatch scheduling and revenue tracking.",
      tech: ["Next.js", "NestJS", "MongoDB", "GitHub Actions", "Docker"],
      stats: [
        { label: "active users", value: "10k+" },
        { label: "transactions", value: "7,000+" },
        { label: "uptime", value: "99.9%" },
      ],
      role: "Software Engineer · BaggageTAXI FZ-LLC",
    },
    {
      id: "managebee",
      year: "2021–2023",
      title: "ManageBee",
      sub: "SaaS Platform for Property Inspections",
      desc: "A subscription-based web platform for property inspection and reporting. Built the full-stack application including frontend UI, backend services, admin dashboard, and automated PDF report generation.",
      tech: ["React.js", "Node.js", "Express.js", "MongoDB", "Stripe API", "Tailwind CSS"],
      stats: [
        { label: "API speedup", value: "40%" },
        { label: "billing", value: "Stripe" },
        { label: "access", value: "RBAC" },
      ],
      role: "Full Stack Developer · Skyniche Technologies",
    },
    {
      id: "ai-generator",
      year: "2024",
      title: "AI Content Gen",
      sub: "AI-powered SEO Content Generator",
      desc: "AI-powered tool for generating SEO-optimized blog content using OpenAI. Developed UI, integrated OpenAI API, implemented user authentication and content tracking — reduced content generation time by 80%.",
      tech: ["React.js", "Node.js", "OpenAI API", "MongoDB", "JWT", "Docker"],
      stats: [
        { label: "time saved", value: "80%" },
        { label: "AI", value: "OpenAI" },
        { label: "auth", value: "JWT" },
      ],
      role: "Freelance · Solo build",
    },
  ],
  education: {
    degree: "Bachelor of Engineering – Mechanical",
    institution: "Anna University, Chennai, India",
    period: "2012–2016",
  },
  certifications: [
    { title: "JavaScript – Advanced Concepts", issuer: "Udemy", year: "2022" },
    { title: "Web App Development (HTML, CSS & JS)", issuer: "Udemy", year: "2022" },
    { title: "Back-End Development with Node.js", issuer: "Udemy", year: "2022" },
  ],
};
